// Written by tools/sounds/library_pack.mjs. Do not edit by hand: change the
// table in the script and run it again.

import 'package:critalarm/core/sound/sound_pack.dart';

/// The sounds in the library pack, in the order the picker lists them.
const libraryPackSounds = <PackSoundInfo>[
  PackSoundInfo(
    id: 'pack_library_buzzer_1',
    englishName: 'Electronic buzzer 1',
    duration: Duration(milliseconds: 21735),
    title: 'Electronic Alarm (Buzzer) #1',
    author: 'Joseph SARDIN (BigSoundBank)',
    sourceUrl: 'https://bigsoundbank.com/electronic-alarm-buzzer-1-s0035.html',
    licence: 'CC0 1.0',
  ),
  PackSoundInfo(
    id: 'pack_library_buzzer_2',
    englishName: 'Electronic buzzer 2',
    duration: Duration(milliseconds: 10127),
    title: 'Electronic alarm (buzzer) #2',
    author: 'Joseph SARDIN (BigSoundBank)',
    sourceUrl: 'https://bigsoundbank.com/electronic-alarm-buzzer-2-s0089.html',
    licence: 'CC0 1.0',
  ),
  PackSoundInfo(
    id: 'pack_library_buzzer_3',
    englishName: 'Electronic buzzer 3',
    duration: Duration(milliseconds: 10934),
    title: 'Electronic Alarm (Buzzer) #3',
    author: 'Joseph SARDIN (BigSoundBank)',
    sourceUrl: 'https://bigsoundbank.com/electronic-alarm-buzzer-3-s0173.html',
    licence: 'CC0 1.0',
  ),
  PackSoundInfo(
    id: 'pack_library_clock_ring_11',
    englishName: 'Wind-up clock',
    duration: Duration(milliseconds: 13426),
    title: 'Mechanical Alarm Clock, Ringtone #11',
    author: 'Joseph SARDIN (BigSoundBank)',
    sourceUrl:
        'https://bigsoundbank.com/mechanical-alarm-clock-ringtone-11-s2814.html',
    licence: 'CC0 1.0',
  ),
  PackSoundInfo(
    id: 'pack_library_clock_ring_8',
    englishName: 'Wind-up clock, short',
    duration: Duration(milliseconds: 11693),
    title: 'Mechanical alarm clock, ringtone #8',
    author: 'Joseph SARDIN (BigSoundBank)',
    sourceUrl:
        'https://bigsoundbank.com/mechanical-alarm-clock-ringtone-8-s2811.html',
    licence: 'CC0 1.0',
  ),
  PackSoundInfo(
    id: 'pack_library_clock_long_ring',
    englishName: 'Wind-up clock, long ring',
    duration: Duration(milliseconds: 10861),
    title: 'Mechanical alarm clock, long ring #2',
    author: 'Joseph SARDIN (BigSoundBank)',
    sourceUrl:
        'https://bigsoundbank.com/mechanical-alarm-clock-long-ring-2-s1375.html',
    licence: 'CC0 1.0',
  ),
  PackSoundInfo(
    id: 'pack_library_digital_watch',
    englishName: 'Digital watch',
    duration: Duration(milliseconds: 18803),
    title: 'Digital watch, alarm',
    author: 'Joseph SARDIN (BigSoundBank)',
    sourceUrl: 'https://bigsoundbank.com/digital-watch-alarm-s2256.html',
    licence: 'CC0 1.0',
  ),
  PackSoundInfo(
    id: 'pack_library_piezo_1',
    englishName: 'Piezo alarm 1',
    duration: Duration(milliseconds: 15860),
    title: 'Piezo Alarm #1',
    author: 'Joseph SARDIN (BigSoundBank)',
    sourceUrl: 'https://bigsoundbank.com/piezo-alarm-1-s1592.html',
    licence: 'CC0 1.0',
  ),
  PackSoundInfo(
    id: 'pack_library_piezo_3',
    englishName: 'Piezo alarm 3',
    duration: Duration(milliseconds: 13764),
    title: 'Piezo alarm #3',
    author: 'Joseph SARDIN (BigSoundBank)',
    sourceUrl: 'https://bigsoundbank.com/piezo-alarm-3-s1996.html',
    licence: 'CC0 1.0',
  ),
  PackSoundInfo(
    id: 'pack_library_buzzer_4',
    englishName: 'Buzzer',
    duration: Duration(milliseconds: 11150),
    title: 'Buzzer #4',
    author: 'Joseph SARDIN (BigSoundBank)',
    sourceUrl: 'https://bigsoundbank.com/buzzer-4-s1586.html',
    licence: 'CC0 1.0',
  ),
  PackSoundInfo(
    id: 'pack_library_industrial_doorbell',
    englishName: 'Industrial doorbell',
    duration: Duration(milliseconds: 11370),
    title: 'Industrial Doorbell #1',
    author: 'Joseph SARDIN (BigSoundBank)',
    sourceUrl: 'https://bigsoundbank.com/industrial-doorbell-s1269.html',
    licence: 'CC0 1.0',
  ),
  PackSoundInfo(
    id: 'pack_library_boxing_bell',
    englishName: 'Boxing bell',
    duration: Duration(milliseconds: 12293),
    title: 'Boxing Bell #2',
    author: 'Joseph SARDIN (BigSoundBank)',
    sourceUrl: 'https://bigsoundbank.com/boxing-bell-2-s1927.html',
    licence: 'CC0 1.0',
  ),
  PackSoundInfo(
    id: 'pack_library_dive_klaxon',
    englishName: 'Dive klaxon',
    duration: Duration(milliseconds: 11420),
    title: 'WWII submarine dive klaxon',
    author: 'United States Navy',
    sourceUrl:
        'https://commons.wikimedia.org/wiki/File:WWII_submarine_dive_klaxon.ogg',
    licence: 'Public domain (PD-USGov-Military-Navy)',
  ),
  PackSoundInfo(
    id: 'pack_library_school_bell',
    englishName: 'School bell',
    duration: Duration(milliseconds: 20494),
    title: 'Old school bell - 1',
    author: 'ezwa (pdsounds.org)',
    sourceUrl: 'https://commons.wikimedia.org/wiki/File:Old_school_bell_1.ogg',
    licence: 'Public domain (PD-author, via pdsounds.org)',
  ),
  PackSoundInfo(
    id: 'pack_library_school_bell_short',
    englishName: 'School bell, short',
    duration: Duration(milliseconds: 13796),
    title: 'Old school bell - 4',
    author: 'ezwa (pdsounds.org)',
    sourceUrl: 'https://commons.wikimedia.org/wiki/File:Old_school_bell_4.ogg',
    licence: 'Public domain (PD-author, via pdsounds.org)',
  ),
  PackSoundInfo(
    id: 'pack_library_buzzwire',
    englishName: 'Buzzwire',
    duration: Duration(milliseconds: 11255),
    title: 'Buzzer (buzzwire tutorial)',
    author: 'David Pride',
    sourceUrl: 'https://commons.wikimedia.org/wiki/File:Buzzer.wav',
    licence: 'CC0 1.0',
  ),
  PackSoundInfo(
    id: 'pack_library_sos_morse',
    englishName: 'SOS in Morse',
    duration: Duration(milliseconds: 12275),
    title: 'SOS in Morse code (synthesized in Audacity)',
    author: 'Hydrargyrum',
    sourceUrl: 'https://commons.wikimedia.org/wiki/File:SOS_morse_code.ogg',
    licence: 'Public domain (PD-self)',
  ),
  PackSoundInfo(
    id: 'pack_library_toy_siren',
    englishName: 'Toy fire engine',
    duration: Duration(milliseconds: 20322),
    title: 'Toy Siren Alarm (toy fire engine)',
    author: 'stephan (pdsounds.org)',
    sourceUrl: 'https://commons.wikimedia.org/wiki/File:Toy_siren_alarm.ogg',
    licence: 'Public domain (PD-author, via pdsounds.org)',
  ),
  PackSoundInfo(
    id: 'pack_library_heart_monitor',
    englishName: 'Heart monitor',
    duration: Duration(milliseconds: 27179),
    title: 'Heart Monitor Beep',
    author: 'samfk360 (Freesound 148897)',
    sourceUrl:
        'https://commons.wikimedia.org/wiki/File:Heart_Monitor_Beep--freesound.org.oga',
    licence: 'CC0 1.0',
  ),
  PackSoundInfo(
    id: 'pack_library_beep_beep',
    englishName: 'Beep beep beep',
    duration: Duration(milliseconds: 19361),
    title: 'Alarm or Siren (synthesized beep-beep-beep)',
    author: 'stephan (pdsounds.org)',
    sourceUrl: 'https://commons.wikimedia.org/wiki/File:Alarm_or_siren.ogg',
    licence: 'Public domain (PD-author, via pdsounds.org)',
  ),
  PackSoundInfo(
    id: 'pack_library_game_alarm',
    englishName: 'Game alarm',
    duration: Duration(milliseconds: 10120),
    title: 'Alarm',
    author: 'Frenchyboy (OpenGameArt)',
    sourceUrl: 'https://opengameart.org/content/alarm-2',
    licence: 'CC0 1.0',
  ),
  PackSoundInfo(
    id: 'pack_library_synth_alarm',
    englishName: 'Synth alarm',
    duration: Duration(milliseconds: 11203),
    title: 'Alarm sound effect (made with jfxr)',
    author: 'bonzille (OpenGameArt)',
    sourceUrl: 'https://opengameart.org/content/alarm-sound-effect',
    licence: 'CC0 1.0',
  ),
  PackSoundInfo(
    id: 'pack_library_short_alarm',
    englishName: 'Short alarm',
    duration: Duration(milliseconds: 10106),
    title: 'Short alarm',
    author: 'yd (OpenGameArt)',
    sourceUrl: 'https://opengameart.org/content/short-alarm',
    licence: 'CC0 1.0',
  ),
];
