// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDJwaAMhn2MUAq6au1dBZbXyX0LgdFnLGE',
    appId: '1:114582883538:web:23a4575b8527befb1db10b',
    messagingSenderId: '114582883538',
    projectId: 'crit-alarm',
    authDomain: 'crit-alarm.firebaseapp.com',
    storageBucket: 'crit-alarm.firebasestorage.app',
    measurementId: 'G-LF6J4BS16J',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCfKGtzZ9CamIJuF09D57V4i61oB9AmONQ',
    appId: '1:114582883538:android:88b8fee01ac430df1db10b',
    messagingSenderId: '114582883538',
    projectId: 'crit-alarm',
    storageBucket: 'crit-alarm.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAgXEJB1gPHE-6kCE6qSAVIcv039VyHtvs',
    appId: '1:114582883538:ios:f660c3c8df2290a11db10b',
    messagingSenderId: '114582883538',
    projectId: 'crit-alarm',
    storageBucket: 'crit-alarm.firebasestorage.app',
    iosBundleId: 'app.critalarm',
  );
}
