#!/usr/bin/env bash
#
# Write ios/Flutter/Google.xcconfig from .env.
#
# Google Sign-In on iOS only starts its flow if the app bundle registers the
# reversed client id as a URL scheme. iOS reads URL schemes out of Info.plist at
# install time, so this one value cannot come from .env at runtime the way every
# other key in this app does. Info.plist carries $(GOOGLE_REVERSED_CLIENT_ID)
# and this script fills it.
#
# The generated file is gitignored, so the client id stays out of this public
# repo. Run this before any iOS build. The Makefile targets already do.
#
# The reversed id is the forward one with the domain turned around:
#
#   1145...-fh6e....apps.googleusercontent.com
#   com.googleusercontent.apps.1145...-fh6e...
#
# So there is nothing new to put in .env. GOOGLE_IOS_CLIENT_ID is enough.

set -euo pipefail

cd "$(dirname "$0")/.."

env_file=".env"
out="ios/Flutter/Google.xcconfig"

if [ ! -f "$env_file" ]; then
  echo "gen-google-xcconfig: $env_file is missing. Copy .env.example and fill it in." >&2
  exit 1
fi

client_id="$(grep -E '^GOOGLE_IOS_CLIENT_ID=' "$env_file" | head -n 1 | cut -d= -f2- | tr -d '"'"'"' \r')"

# An empty value here is the whole reason this script exists. Xcode is happy to
# substitute an empty string into Info.plist, which builds an app whose Google
# sign-in fails with no clue why. Fail here instead, while somebody is watching.
if [ -z "$client_id" ]; then
  echo "gen-google-xcconfig: GOOGLE_IOS_CLIENT_ID is empty in $env_file." >&2
  echo "  Google sign-in on iOS cannot work without it. The value is the CLIENT_ID" >&2
  echo "  in secrets/google-oauth-ios.plist." >&2
  exit 1
fi

case "$client_id" in
  *.apps.googleusercontent.com) ;;
  *)
    echo "gen-google-xcconfig: GOOGLE_IOS_CLIENT_ID does not look like a Google client id:" >&2
    echo "  $client_id" >&2
    echo "  Expected something ending in .apps.googleusercontent.com" >&2
    exit 1
    ;;
esac

# Turn 1145...-fh6e....apps.googleusercontent.com into
# com.googleusercontent.apps.1145...-fh6e...
prefix="${client_id%.apps.googleusercontent.com}"
reversed="com.googleusercontent.apps.$prefix"

mkdir -p "$(dirname "$out")"
cat > "$out" <<EOF
// GENERATED by scripts/gen-google-xcconfig.sh from .env. Do not edit, and do
// not commit: this file is gitignored so the client id stays out of a public
// repo. Info.plist reads GOOGLE_REVERSED_CLIENT_ID to register the URL scheme
// Google Sign-In needs.
GOOGLE_REVERSED_CLIENT_ID = $reversed
EOF

echo "gen-google-xcconfig: wrote $out"
