// Custom Flutter web bootstrap (Flutter substitutes the {{...}} tokens at
// build time; providing this file overrides the auto-generated bootstrap).
//
// iOS PWA safe-area fix (flutter/flutter#84833): on iOS, Flutter web sizes its
// view from document.documentElement.clientHeight/clientWidth, which ignore
// viewport-fit=cover and leave the view pushed under the status bar / a blank
// band. Override those getters to the visual-viewport size so the Flutter view
// fills the screen — this also keeps the hit-test grid aligned with the real
// pointer coordinates.
Object.defineProperty(document.documentElement, 'clientHeight', {
  get: () => window.innerHeight,
});

Object.defineProperty(document.documentElement, 'clientWidth', {
  get: () => window.innerWidth,
});

// The Flutter engine rewrites the viewport meta at boot (and can rewrite it
// again later) WITHOUT viewport-fit=cover, which zeroes every
// env(safe-area-inset-*) in an iOS standalone PWA. Keep re-appending it
// whenever the tag changes.
(() => {
  const ensureViewportFit = () => {
    const meta = document.querySelector('meta[name=viewport]');
    if (meta && !meta.content.includes('viewport-fit=cover')) {
      meta.content += ', viewport-fit=cover';
    }
  };
  ensureViewportFit();
  new MutationObserver(ensureViewportFit).observe(document.head, {
    subtree: true,
    childList: true,
    attributes: true,
    attributeFilter: ['content'],
  });
})();

// Offline support: register the precache worker generated by
// tool/pwa/gen_sw.dart (Flutter's own flutter_service_worker.js is a
// non-caching cleanup stub and is never registered). Registration waits a few
// seconds so the ~40 MB precache download doesn't compete with engine boot on
// a cold load. storage.persist() asks the browser not to evict the cache
// (matters on iOS, which prunes storage of rarely used origins).
if ('serviceWorker' in navigator) {
  window.addEventListener('load', () => {
    setTimeout(() => {
      navigator.serviceWorker
        .register('sw.js')
        .then((registration) => registration.update())
        .catch((error) => console.warn('sw.js registration failed:', error));
      if (navigator.storage && navigator.storage.persist) {
        navigator.storage.persist();
      }
    }, 3000);
  });
}

{{flutter_js}}
{{flutter_build_config}}

_flutter.loader.load();
